version: '3.8'

networks:
  local:

services:
  grafana:
    container_name: "grafana"
    image: grafana/grafana:7.5.5
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana/dashboards/local.yml:/etc/grafana/provisioning/dashboards/local.yml
      - ./grafana/datasources/influxdb.yml:/etc/grafana/provisioning/datasources/influxdb.yml
      - ./grafana/dashboards/dashboard.json:/var/lib/grafana/dashboards/dashboards.json
    networks:
      - local
    depends_on:
      - postgres
      - fruit
      - influxdb
  influxdb:
    container_name: "influxdb"
    image: influxdb:1.8.5-alpine
    ports:
      - "8083:8083"
      - "8086:8086"
      - "2003:2003"
    environment:
      - INFLUXDB_DB=gatlingdb
    volumes:
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
    networks:
      - local
    depends_on:
      - postgres
      - fruit
  fruit:
    container_name: "fruit"
    image: serrodcal/quarkus-fruit-performance:1.0.0
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=vertx-reactive:postgresql://postgres:5432/quarkus_test
    networks:
      - local
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 300M
        reservations:
          memory: 300M
  postgres:
    container_name: "postgres"
    image: postgres:10.15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=quarkus_test
      - POSTGRES_PASSWORD=quarkus_test
      - POSTGRES_DB=quarkus_test
    networks:
      - local